# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Parsa Shams
email: parsa-a-shams-at-gmail-dot-com
description: > # this means to ignore newlines until "baseurl:"
  Home page of parsa shams. Parsa is a Data Scientist, and currently lives in Washington, DC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.parsashams.com" # the base hostname & protocol for your site
twitter_username: parsashams
github_username:  parsashams

# Build settings
markdown: kramdown
